---
apiVersion: batch/v1
kind: Job
metadata:
  name: test-images
spec:
  template:
    spec:
      initContainers:
      - name: init-git
        image: alpine/git
        command: ["sh", "-c"]
        args: 
          - |
            git clone -b develop https://github.com/jyje/pilot-mlops-cicd.git /workspace
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      containers:
      - name: main
        image: python:3.12-slim
        command: ["sh", "-c"]
        args: 
          - |
            cd /workspace/sources && \
            pip install --upgrade pip && \
            pip install -r requirements.txt && \
            python -u model-client.py \
              --server-host "${SERVER_HOST}" \
              --model-name "${MODEL_NAME}" \
              --model-version "${MODEL_VERSION}" \
              --image-url "https://raw.githubusercontent.com/jyje/pilot-mlops-cicd/refs/heads/develop/assets/sample_images/0a.png" && \
            python -u model-client.py \
              --server-host "${SERVER_HOST}" \
              --model-name "${MODEL_NAME}" \
              --model-version "${MODEL_VERSION}" \
              --image-url "https://raw.githubusercontent.com/jyje/pilot-mlops-cicd/refs/heads/develop/assets/sample_images/0b.png" && \
            python -u model-client.py \
              --server-host "${SERVER_HOST}" \
              --model-name "${MODEL_NAME}" \
              --model-version "${MODEL_VERSION}" \
              --image-url "https://raw.githubusercontent.com/jyje/pilot-mlops-cicd/refs/heads/develop/assets/sample_images/1a.png" && \
            python -u model-client.py \
              --server-host "${SERVER_HOST}" \
              --model-name "${MODEL_NAME}" \
              --model-version "${MODEL_VERSION}" \
              --image-url "https://raw.githubusercontent.com/jyje/pilot-mlops-cicd/refs/heads/develop/assets/sample_images/1b.png" && \
            python -u model-client.py \
              --server-host "${SERVER_HOST}" \
              --model-name "${MODEL_NAME}" \
              --model-version "${MODEL_VERSION}" \
              --image-url "https://raw.githubusercontent.com/jyje/pilot-mlops-cicd/refs/heads/develop/assets/sample_images/2a.png" && \
            python -u model-client.py \
              --server-host "${SERVER_HOST}" \
              --model-name "${MODEL_NAME}" \
              --model-version "${MODEL_VERSION}" \
              --image-url "https://raw.githubusercontent.com/jyje/pilot-mlops-cicd/refs/heads/develop/assets/sample_images/2b.png" && \
            python -u model-client.py \
              --server-host "${SERVER_HOST}" \
              --model-name "${MODEL_NAME}" \
              --model-version "${MODEL_VERSION}" \
              --image-url "https://raw.githubusercontent.com/jyje/pilot-mlops-cicd/refs/heads/develop/assets/sample_images/3a.png" && \
            python -u model-client.py \
              --server-host "${SERVER_HOST}" \
              --model-name "${MODEL_NAME}" \
              --model-version "${MODEL_VERSION}" \
              --image-url "https://raw.githubusercontent.com/jyje/pilot-mlops-cicd/refs/heads/develop/assets/sample_images/3b.png" && \
            python -u model-client.py \
              --server-host "${SERVER_HOST}" \
              --model-name "${MODEL_NAME}" \
              --model-version "${MODEL_VERSION}" \
              --image-url "https://raw.githubusercontent.com/jyje/pilot-mlops-cicd/refs/heads/develop/assets/sample_images/4a.png" && \
            python -u model-client.py \
              --server-host "${SERVER_HOST}" \
              --model-name "${MODEL_NAME}" \
              --model-version "${MODEL_VERSION}" \
              --image-url "https://raw.githubusercontent.com/jyje/pilot-mlops-cicd/refs/heads/develop/assets/sample_images/4b.png" && \
            python -u model-client.py \
              --server-host "${SERVER_HOST}" \
              --model-name "${MODEL_NAME}" \
              --model-version "${MODEL_VERSION}" \
              --image-url "https://raw.githubusercontent.com/jyje/pilot-mlops-cicd/refs/heads/develop/assets/sample_images/5a.png" && \
            python -u model-client.py \
              --server-host "${SERVER_HOST}" \
              --model-name "${MODEL_NAME}" \
              --model-version "${MODEL_VERSION}" \
              --image-url "https://raw.githubusercontent.com/jyje/pilot-mlops-cicd/refs/heads/develop/assets/sample_images/5b.png" && \
            python -u model-client.py \
              --server-host "${SERVER_HOST}" \
              --model-name "${MODEL_NAME}" \
              --model-version "${MODEL_VERSION}" \
              --image-url "https://raw.githubusercontent.com/jyje/pilot-mlops-cicd/refs/heads/develop/assets/sample_images/6a.png" && \
            python -u model-client.py \
              --server-host "${SERVER_HOST}" \
              --model-name "${MODEL_NAME}" \
              --model-version "${MODEL_VERSION}" \
              --image-url "https://raw.githubusercontent.com/jyje/pilot-mlops-cicd/refs/heads/develop/assets/sample_images/6b.png" && \
            python -u model-client.py \
              --server-host "${SERVER_HOST}" \
              --model-name "${MODEL_NAME}" \
              --model-version "${MODEL_VERSION}" \
              --image-url "https://raw.githubusercontent.com/jyje/pilot-mlops-cicd/refs/heads/develop/assets/sample_images/7a.png" && \
            python -u model-client.py \
              --server-host "${SERVER_HOST}" \
              --model-name "${MODEL_NAME}" \
              --model-version "${MODEL_VERSION}" \
              --image-url "https://raw.githubusercontent.com/jyje/pilot-mlops-cicd/refs/heads/develop/assets/sample_images/7b.png" && \
            python -u model-client.py \
              --server-host "${SERVER_HOST}" \
              --model-name "${MODEL_NAME}" \
              --model-version "${MODEL_VERSION}" \
              --image-url "https://raw.githubusercontent.com/jyje/pilot-mlops-cicd/refs/heads/develop/assets/sample_images/8a.png" && \
            python -u model-client.py \
              --server-host "${SERVER_HOST}" \
              --model-name "${MODEL_NAME}" \
              --model-version "${MODEL_VERSION}" \
              --image-url "https://raw.githubusercontent.com/jyje/pilot-mlops-cicd/refs/heads/develop/assets/sample_images/8b.png" && \
            python -u model-client.py \
              --server-host "${SERVER_HOST}" \
              --model-name "${MODEL_NAME}" \
              --model-version "${MODEL_VERSION}" \
              --image-url "https://raw.githubusercontent.com/jyje/pilot-mlops-cicd/refs/heads/develop/assets/sample_images/9a.png" && \
            python -u model-client.py \
              --server-host "${SERVER_HOST}" \
              --model-name "${MODEL_NAME}" \
              --model-version "${MODEL_VERSION}" \
              --image-url "https://raw.githubusercontent.com/jyje/pilot-mlops-cicd/refs/heads/develop/assets/sample_images/9b.png" && \
            echo "Done"
        envFrom:
        - configMapRef:
            name: model-client
        volumeMounts:
        - name: workspace
          mountPath: /workspace
          readOnly: true
      volumes:
      - name: workspace
        emptyDir: {}
      restartPolicy: Never
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: model-client
data:
  SERVER_HOST: "model-server:8001"
  MODEL_NAME: "pilot"
  MODEL_VERSION: "1"
