
name: "pilot-cpu"
platform: "pytorch_libtorch"
max_batch_size: 8
input [
    {
        name: "x.1"
        data_type: TYPE_FP32
        dims: [ 3, 224, 224 ]
    }
]
output [
    {
        name: "4"
        data_type: TYPE_FP32
        dims: [ 10 ]
    }
]
